services:
    webapp:
        build: .
        container_name: flask-webapp
        env_file:
            - .env
        ports:
            - "5000:5000"
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql-container 
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_ROOT_PASSWORD : ${DB_ROOT_PASSWORD}


